name: ETL BigQuery

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Call /load
        run: |
          curl -fsS "https://kalena-pnl--kalenaweb.us-east4.hosted.app/load" || exit 1

      - name: Call /update
        run: |
          curl -fsS "https://kalena-pnl--kalenaweb.us-east4.hosted.app/update" || exit 1
